### ISSUE TITLE
How to move the lightbox to the background / foreground?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1899]
My ligthbox contains a button to expand a spherical panorama in a special viewer.

Before I do that, I hide the lightbox with this code:

```
function lightboxHide() {
    const x = document.querySelector('.pswp');
    x.style.display = "none";
}
```

If the special viewer is closed, I show the lightbox again with this code:

```
function lightboxShow() {
    const x = document.querySelector('.pswp');
    if (x.style.display === "none") {
        x.style.display = "block";
    }
}
```

This gives a problem, if I click the Next button I get a crash:

```
 Uncaught TypeError: Cannot read properties of undefined (reading 'applyCurrentZoomPan')
    at T.updateCurrItem (photoswipe.esm.min.js:5:20446)
    at onComplete (photoswipe.esm.min.js:5:19430)
    at u (photoswipe.esm.min.js:5:23335)
```

I can't find the cause of this problem, but I don't get this crash if I don't call  lightboxHide and  lightboxShow. However in that case the special viewer is displayed in the background and I see the ligthbox in the foreground.

So my question is:

What code is required to move the ligthbox to the background

and later back to the foreground?

**Comment by acwolff** [comment]
@dimsemenov  this did solve the problem:

```
function lightboxHide() {
    const x = document.querySelector('.pswp');
    x.style.visibility = "hidden";
}

function lightboxShow() {
    const x = document.querySelector('.pswp');
    x.style.visibility = "visible";
}
```
Thanks for your quick help and your awesome library!

**Comment by acwolff** [comment]
@dimsemenov I have no custom arrows outside.

The problem is solved with this code:
```
function lightboxHide() {
    const x = document.querySelector('.pswp');
    const p = document.querySelector('.pswp__button--arrow--prev');
    const n = document.querySelector('.pswp__button--arrow--next');
    x.style.visibility = "hidden";
    p.style.visibility = "hidden";
    n.style.visibility = "hidden";
}

function lightboxShow() {
    const x = document.querySelector('.pswp');
    const p = document.querySelector('.pswp__button--arrow--prev');
    const n = document.querySelector('.pswp__button--arrow--next');
    x.style.visibility = "visible";
    p.style.visibility = "visible";
    n.style.visibility = "visible";
}
```
To see this in action open [this page](https://andrewolff.jalbum.net/PS_SpherePan_PSV4/?M1) and click on the expand button in the upper right corner.

Thanks again  for your quick help!
